# Generated by Django 5.1.1 on 2024-09-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='users',
        ),
    ]
